# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
    build:
        branches:
              ignore:
                     - gh-pages
        docker:
        # specify the version you desire here
        - image: circleci/node:8

        # Specify service dependencies here if necessary
        # CircleCI maintains a library of pre-built images
        # documented at https://circleci.com/docs/2.0/circleci-images/
        # - image: circleci/mongo:3.4.4
        environment:
              - SOURCE_BRANCH: master
              - TARGET_BRANCH: gh-pages
        steps:
        - checkout

        # Download and cache dependencies
        - restore_cache:
              keys:
              - v1-dependencies-{{ checksum "scratch-gui/package.json" }}
              - v1-dependencies-{{ checksum "scratch-vm/package.json" }}
              # fallback to using the latest cache if no exact match is found
              - v1-dependencies-
        - run: 
            name: Build and Deploy
            command: |
                  if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then
                        git config --global user.email $GH_EMAIL
                        git config --global user.name $GH_NAME

                        git clone $CIRCLE_REPOSITORY_URL out

                        cd out
                        git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
                        git rm -rf .
                        cd ..
                        cd scratch-vm
                        npm install
                        sudo npm link
                        #npm run watch
                        cd ../scratch-gui
                        npm install
                        sudo npm link scratch-vm
                        npm run build
                        cd ..
                        cp -a scratch-gui/build/. out/.

                        mkdir -p out/.circleci && cp -a .circleci/. out/.circleci/.
                        cd out

                        git add -A
                        git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty

                        git push origin $TARGET_BRANCH
                  fi
        - save_cache:
              paths:
              - scratch-vm/node_modules
              key: v1-dependencies-{{ checksum "scratch-vm/package.json" }}

        - save_cache:
              paths:
              - scratch-gui/node_modules
              key: v1-dependencies-{{ checksum "scratch-gui/package.json" }}